/**
 * SYMBION KERNEL - OpenAPI/Swagger Documentation (K8)
 *
 * RÔLE : Génération automatique de la documentation API au format OpenAPI 3.1
 * Sert le fichier JSON à /api-docs/openapi.json et Swagger UI à /swagger-ui/
 *
 * UTILITÉ : Documentation toujours synchronisée avec le code, interface de test interactive
 */

use utoipa::OpenApi;
use utoipa::openapi::security::{Http, HttpAuthScheme, SecurityScheme};

#[derive(OpenApi)]
#[openapi(
    info(
        title = "Symbion Kernel API",
        version = "1.0.0",
        description = "API REST du kernel Symbion — système d'automatisation personnelle et domotique intelligente",
        license(name = "Proprietary")
    ),
    paths(
        // System
        crate::http::system::health_readiness_check,
        crate::http::system::get_system_health,
        crate::http::system::prometheus_metrics_endpoint,
        crate::http::system::get_metrics_agents,
        crate::http::system::get_metrics_system,
        crate::http::system::get_hosts,
        crate::http::system::get_host,
        crate::http::system::wake,
        crate::http::system::list_contracts,
        crate::http::system::get_contract,
        crate::http::system::get_logs,
        // Authentication
        crate::http::auth::auth_login,
        crate::http::auth::auth_verify,
        crate::http::auth::auth_session,
        crate::http::auth::auth_logout,
        crate::http::auth::auth_reload_users,
        crate::http::auth::create_user,
        crate::http::auth::delete_user,
        crate::http::auth::list_users,
        crate::http::auth::update_user_password,
        crate::http::auth::mfa_status,
        crate::http::auth::mfa_setup,
        crate::http::auth::mfa_verify,
        crate::http::auth::mfa_disable,
        crate::http::auth::csrf_generate_nonce,
        crate::http::auth::download_ca_certificate,
        crate::http::auth::webauthn_register_start,
        crate::http::auth::webauthn_register_finish,
        crate::http::auth::webauthn_list_passkeys,
        crate::http::auth::webauthn_delete_passkey,
        crate::http::auth::webauthn_authenticate_start,
        crate::http::auth::webauthn_authenticate_discoverable_start,
        crate::http::auth::webauthn_authenticate_finish,
        // Agents
        crate::http::agents::list_agents_endpoint,
        crate::http::agents::get_agent_endpoint,
        crate::http::agents::delete_agent_endpoint,
        crate::http::agents::agent_shutdown_endpoint,
        crate::http::agents::agent_reboot_endpoint,
        crate::http::agents::agent_hibernate_endpoint,
        crate::http::agents::agent_reconnect_endpoint,
        crate::http::agents::agent_processes_endpoint,
        crate::http::agents::agent_kill_process_endpoint,
        crate::http::agents::agent_command_endpoint,
        crate::http::agents::agent_metrics_endpoint,
        crate::http::agents::agent_commands_endpoint,
        crate::http::agents::agent_commands_post_endpoint,
        crate::http::agents::cancel_command_endpoint,
        crate::http::agents::command_status_endpoint,
        crate::http::agents::start_plugin_systemctl,
        crate::http::agents::stop_plugin_systemctl,
        crate::http::agents::restart_plugin_systemctl,
        crate::http::agents::get_plugin_systemctl_status,
        crate::http::agents::delete_sensor_endpoint,
        // Context
        crate::http::context::get_context_current,
        crate::http::context::set_context_override,
        crate::http::context::clear_context_override,
        crate::http::context::get_context_history,
        crate::http::context::get_context_stats,
        crate::http::context::get_context_productivity,
        // Modes
        crate::http::context::list_modes,
        crate::http::context::get_mode,
        crate::http::context::create_mode,
        crate::http::context::update_mode,
        crate::http::context::delete_mode,
        // Schedule
        crate::http::context::get_schedule,
        crate::http::context::list_schedule_rules,
        crate::http::context::get_current_schedule_mode,
        crate::http::context::create_schedule_rule,
        crate::http::context::update_schedule_rule,
        crate::http::context::delete_schedule_rule,
        crate::http::context::set_schedule_default_mode,
        // Decision
        crate::http::decision::decision_evaluate,
        crate::http::decision::decision_get_audit,
        crate::http::decision::decision_get_metrics,
        crate::http::decision::decision_list_pending_validations,
        crate::http::decision::decision_resolve_validation,
        crate::http::decision::decision_create_override,
        crate::http::decision::decision_list_active_overrides,
        crate::http::decision::decision_revoke_override,
        crate::http::decision::decision_get_config,
        crate::http::decision::decision_get_agent_health,
        crate::http::decision::decision_get_stats,
        crate::http::decision::decision_list_expired_validations,
        crate::http::decision::decision_delete_validation,
        crate::http::decision::decision_delete_all_expired_validations,
        // Notifications
        crate::http::notifications::list_notifications,
        crate::http::notifications::list_active_notifications,
        crate::http::notifications::list_fcm_tokens,
        crate::http::notifications::send_notification,
        crate::http::notifications::acknowledge_notification,
        crate::http::notifications::delete_notification,
        crate::http::notifications::delete_all_notifications,
        crate::http::notifications::register_fcm_token,
        crate::http::notifications::list_notification_configs,
        crate::http::notifications::get_notification_config,
        crate::http::notifications::update_notification_config,
        // Environment
        crate::environment_http::list_sensors,
        crate::environment_http::get_sensor,
        crate::environment_http::get_sensor_history,
        crate::environment_http::get_room_environment,
        crate::environment_http::get_room_history,
        // Intelligence
        crate::intelligence_http::get_status,
        crate::intelligence_http::get_health,
        crate::intelligence_http::get_patterns,
        crate::intelligence_http::get_predictions,
        crate::intelligence_http::get_signals,
        crate::intelligence_http::post_feedback,
        crate::intelligence_http::get_config,
        crate::intelligence_http::put_config,
        crate::intelligence_http::get_patterns_export,
        crate::intelligence_http::get_features,
        crate::intelligence_http::post_feature,
        crate::intelligence_http::get_vector,
        crate::intelligence_http::get_prediction2,
        crate::intelligence_http::get_session,
        crate::intelligence_http::get_shadow_stats,
        // Automations
        crate::automations_http::list_automations,
        crate::automations_http::get_automation,
        crate::automations_http::get_automations_schema,
        crate::automations_http::get_automations_history,
        crate::automations_http::create_automation,
        crate::automations_http::update_automation,
        crate::automations_http::delete_automation,
        crate::automations_http::toggle_automation,
        crate::automations_http::test_automation,
        crate::automations_http::run_automation,
    ),
    components(schemas(
        // System
        crate::http::system::HostView,
        crate::http::system::WakeParams,
        crate::http::system::AgentMetrics,
        crate::http::system::AgentCpuMetrics,
        crate::http::system::AgentMemoryMetrics,
        crate::http::system::AgentDiskMetrics,
        crate::http::system::AgentNetworkMetrics,
        crate::http::system::AgentProcessMetrics,
        crate::http::system::SystemMetrics,
        crate::http::system::KernelRuntimeMetrics,
        crate::http::system::MqttMetrics,
        crate::http::system::AgentsSummaryMetrics,
        crate::http::system::PluginsMetrics,
        crate::http::system::ContextMetrics,
        crate::http::system::DecisionEngineMetrics,
        crate::http::system::LogsQuery,
        crate::http::system::LogEntry,
        crate::contracts::Contract,
        crate::health::KernelHealth,
        // Auth
        crate::http::auth::CreateUserRequest,
        crate::http::auth::UpdatePasswordRequest,
        crate::http::auth::MfaSetupRequest,
        crate::http::auth::MfaSetupResponse,
        crate::http::auth::MfaVerifyRequest,
        crate::http::auth::WebAuthnRegisterStartRequest,
        crate::http::auth::WebAuthnAuthenticateStartRequest,
        // Agents
        crate::http::agents::AgentView,
        crate::http::agents::AgentCommandRequest,
        crate::http::agents::AgentCommandTrackingRequest,
        crate::agents::Agent,
        crate::agents::AgentNetwork,
        crate::agents::AgentInterface,
        crate::agents::AgentStatus,
        crate::agents::AgentSystemMetrics,
        crate::agents::AgentCpuMetrics,
        crate::agents::AgentMemoryMetrics,
        crate::agents::AgentDiskMetrics,
        crate::agents::AgentNetworkMetrics,
        crate::agents::AgentNetworkInterface,
        crate::agents::AgentTemperatureMetrics,
        crate::agents::AgentTemperatureSensor,
        crate::agents::AgentProcesses,
        crate::agents::AgentProcess,
        crate::agents::AgentService,
        crate::agents::AgentCommand,
        crate::agents::AgentCommandResponse,
        crate::agents::AgentLastCommand,
        crate::agents::CommandStatus,
        crate::agents::PendingCommand,
        crate::agents::AgentResponse,
        // Context
        crate::http::context::ContextOverrideRequest,
        crate::context::ContextState,
        crate::context::ManualOverride,
        crate::context::ModeHistoryEntry,
        crate::context::ModeStats,
        crate::context::ProductivityMetrics,
        crate::context::Theme,
        crate::context::Mode,
        // Modes
        crate::modes::types::ModeTheme,
        crate::modes::types::DynamicMode,
        crate::modes::types::CreateModeRequest,
        crate::modes::types::UpdateModeRequest,
        // Schedule
        crate::schedule::types::Schedule,
        crate::schedule::types::ScheduleRule,
        crate::schedule::types::CreateRuleRequest,
        crate::schedule::types::UpdateRuleRequest,
        crate::schedule::types::UpdateDefaultModeRequest,
        crate::schedule::types::CurrentScheduleInfo,
        // Decision
        crate::decision_http::EvaluateRequest,
        crate::decision_http::AuditQueryParams,
        crate::decision_http::ResolveValidationRequest,
        crate::decision_http::CreateOverrideRequest,
        crate::decision_http::RevokeOverrideRequest,
        crate::decision_http::DecisionStats,
        crate::decision::types::DecisionResult,
        crate::decision::types::DecisionConfig,
        crate::decision::types::ImpactLevel,
        crate::decision::types::Action,
        crate::decision::types::DecisionContext,
        crate::decision::types::AgentState,
        crate::decision::types::DecisionRecord,
        crate::decision::types::TrustCriteria,
        crate::decision::types::TrustScore,
        crate::decision::types::TrustWeights,
        crate::decision::types::ImpactThresholds,
        crate::decision::validation::ValidationRequest,
        crate::decision::validation::ValidationStatus,
        crate::decision::r#override::MasterOverride,
        crate::decision::r#override::OverrideType,
        // Notifications
        crate::http::notifications::SendNotificationRequest,
        crate::http::notifications::RegisterFcmTokenRequest,
        crate::notifications::Notification,
        crate::notifications::NotificationAction,
        crate::notifications::FcmToken,
        crate::notification_config::NotificationTypeConfig,
        // Environment
        crate::environment_http::SensorsListResponse,
        crate::environment_http::SensorDetailResponse,
        crate::sensors::Sensor,
        // Intelligence
        crate::intelligence_http::IntelligenceStatusResponse,
        crate::intelligence_http::PatternsResponse,
        crate::intelligence_http::PredictionsResponse,
        crate::intelligence_http::SignalsResponse,
        crate::intelligence_http::FeedbackRequest,
        crate::intelligence_http::FeedbackResponse,
        crate::intelligence_http::FeaturesResponse,
        crate::intelligence_http::VectorResponse,
        crate::intelligence_http::Prediction2Response,
        crate::intelligence_http::ShadowStatsResponse,
        crate::intelligence_http::SessionResponse,
        crate::intelligence_http::SetFeatureRequest,
        crate::intelligence_http::HealthResponse,
        crate::intelligence_http::ConfigResponse,
        crate::intelligence_http::PatternExportQuery,
        crate::intelligence_http::PatternExportResponse,
        crate::intelligence::types::IntelligenceStatus,
        crate::intelligence::types::LearnedPattern,
        crate::intelligence::types::ModePrediction,
        crate::intelligence::types::PredictionRecord,
        crate::intelligence::types::ContextSignals,
        crate::intelligence::types::HealthCounters,
        crate::intelligence::types::AccuracyStats,
        crate::intelligence::config::IntelligenceConfig,
        crate::intelligence::types::PatternExport,
        crate::intelligence::features::FeatureSample,
        crate::intelligence::features::FeatureRegistrySummary,
        crate::intelligence::features::FeatureValue,
        crate::intelligence::vector::ContextVector,
        crate::intelligence::inference::PredictionV2,
        crate::intelligence::inference::InferenceStats,
        crate::intelligence::inference::SampleStats,
        crate::intelligence::types::ShadowStats,
        crate::intelligence::config::V2StabilizationConfig,
        // Automations
        crate::automations::types::Automation,
        crate::automations::types::AutomationRequest,
        crate::automations::types::AutomationsListResponse,
        crate::automations::types::ExecutionRecord,
        crate::automations::types::ToggleRequest,
        crate::automations::types::TestResult,
        crate::automations::types::ActionDefinition,
    )),
    tags(
        (name = "System", description = "Health, metrics, logs, contracts"),
        (name = "Authentication", description = "Login, JWT, MFA, WebAuthn, CSRF"),
        (name = "Agents", description = "Agent registry, commands, telemetry"),
        (name = "Context", description = "Context engine, current mode, history"),
        (name = "Modes", description = "Dynamic modes with custom themes"),
        (name = "Schedule", description = "Time-based scheduling for mode changes"),
        (name = "Decision", description = "Decision engine, validations, overrides, audit"),
        (name = "Automations", description = "Automation rules engine, triggers, actions"),
        (name = "Notifications", description = "FCM push, notification types, tokens"),
        (name = "Environment", description = "IoT sensors, environment monitoring"),
        (name = "Intelligence", description = "Context intelligence, patterns, predictions, features"),
    ),
    modifiers(&SecurityAddon),
)]
pub struct ApiDoc;

struct SecurityAddon;

impl utoipa::Modify for SecurityAddon {
    fn modify(&self, openapi: &mut utoipa::openapi::OpenApi) {
        if let Some(components) = openapi.components.as_mut() {
            let mut http_auth = Http::new(HttpAuthScheme::Bearer);
            http_auth.bearer_format = Some("JWT".to_string());
            components.add_security_scheme(
                "bearer_auth",
                SecurityScheme::Http(http_auth),
            );
        }
    }
}
