/**
 * SYMBION KERNEL - Environment Decision Rules Module (F1)
 *
 * RÔLE : Évaluation règles intelligentes humidité/température pour génération alertes
 *
 * RÈGLES IMPLÉMENTÉES :
 * - ALERT_HUMIDITY_CHAMBRE : Humidité >65% sustained 30 min (Medium impact)
 * - ALERT_HUMIDITY_CRITICAL : Humidité >75% sustained 10 min (High impact)
 * - ALERT_COLD_NIGHT : Température <16°C pendant nuit (Low impact)
 *
 * ARCHITECTURE :
 * - Intention : Type simple pour alertes (intention_type, source, impact, context, timestamp)
 * - EnvironmentRules : Struct stateless avec méthodes d'évaluation
 * - Integration : Appelé par MQTT handler lors ingestion readings
 *
 * FUTURE :
 * - Logging intentions to F3 Intentions Log
 * - Notifications via F4 (PWA + ntfy)
 * - ML prediction patterns (F6+)
 */

use crate::decision::types::ImpactLevel;
use crate::environment::RoomEnvironmentState;
use chrono::{Timelike, Utc};  // Timelike for .hour() method
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Intention = Alert generated by environment rules
///
/// Simpler than DecisionEngine Action (no validation workflow for now)
/// Future: Integrate with F3 Intentions Log for persistence
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Intention {
    pub id: Uuid,
    pub intention_type: String,      // e.g., "ALERT_HUMIDITY_CHAMBRE"
    pub source: String,              // "environment"
    pub impact: ImpactLevel,
    pub context: serde_json::Value,  // Room-specific data
    pub created_at: String,          // ISO 8601 timestamp
}

/// Environment evaluation rules (stateless)
pub struct EnvironmentRules;

impl EnvironmentRules {
    /// Evaluate all environment rules for a room
    ///
    /// Returns list of triggered intentions (empty if no alerts)
    pub fn evaluate_all(state: &RoomEnvironmentState) -> Vec<Intention> {
        let mut intentions = Vec::new();

        // Rule 1: Humidity warning (Medium impact)
        if let Some(intent) = Self::evaluate_humidity_alert(state) {
            intentions.push(intent);
        }

        // Rule 2: Humidity critical (High impact)
        if let Some(intent) = Self::evaluate_humidity_critical(state) {
            intentions.push(intent);
        }

        // Rule 3: Cold night (Low impact)
        if let Some(intent) = Self::evaluate_cold_night(state) {
            intentions.push(intent);
        }

        intentions
    }

    /// Rule: ALERT_HUMIDITY_CHAMBRE
    ///
    /// Trigger: Humidity >65% sustained for 30 minutes
    /// Impact: Medium (health preventive)
    /// Action: Suggest ventilation
    pub fn evaluate_humidity_alert(state: &RoomEnvironmentState) -> Option<Intention> {
        const THRESHOLD: f32 = 65.0;
        const DURATION_MINUTES: u32 = 30;

        // Check sustained humidity
        if !state.is_humidity_sustained(THRESHOLD, DURATION_MINUTES) {
            return None;
        }

        Some(Intention {
            id: Uuid::new_v4(),
            intention_type: "ALERT_HUMIDITY_CHAMBRE".to_string(),
            source: "environment".to_string(),
            impact: ImpactLevel::Medium,
            context: serde_json::json!({
                "room_id": state.room_id,
                "humidity_pct": state.current.humidity_pct,
                "threshold_pct": THRESHOLD,
                "duration_minutes": DURATION_MINUTES,
                "temperature_c": state.current.temperature_c,
                "suggestion": "Aérer la chambre pour réduire l'humidité",
            }),
            created_at: Utc::now().to_rfc3339(),
        })
    }

    /// Rule: ALERT_HUMIDITY_CRITICAL
    ///
    /// Trigger: Humidity >75% sustained for 10 minutes
    /// Impact: High (health critical, mold risk)
    /// Action: Immediate ventilation required
    pub fn evaluate_humidity_critical(state: &RoomEnvironmentState) -> Option<Intention> {
        const THRESHOLD: f32 = 75.0;
        const DURATION_MINUTES: u32 = 10;

        if !state.is_humidity_sustained(THRESHOLD, DURATION_MINUTES) {
            return None;
        }

        Some(Intention {
            id: Uuid::new_v4(),
            intention_type: "ALERT_HUMIDITY_CRITICAL".to_string(),
            source: "environment".to_string(),
            impact: ImpactLevel::High,
            context: serde_json::json!({
                "room_id": state.room_id,
                "humidity_pct": state.current.humidity_pct,
                "threshold_pct": THRESHOLD,
                "duration_minutes": DURATION_MINUTES,
                "status": "risk_mold",
                "urgency": "immediate",
                "suggestion": "Risque moisissure - Aérer immédiatement",
            }),
            created_at: Utc::now().to_rfc3339(),
        })
    }

    /// Rule: ALERT_COLD_NIGHT
    ///
    /// Trigger: Temperature <16°C during night hours (22:00-07:00)
    /// Impact: Low (comfort)
    /// Action: Suggest increase heating
    pub fn evaluate_cold_night(state: &RoomEnvironmentState) -> Option<Intention> {
        const THRESHOLD_TEMP: f32 = 16.0;

        // Check temperature threshold (return None if sensor offline or temp >= threshold)
        let Some(temp) = state.current.temperature_c else {
            return None; // Sensor offline
        };
        if temp >= THRESHOLD_TEMP {
            return None;
        }

        // Check if night hours (22:00-07:00)
        let now = Utc::now();
        let hour = now.hour();
        let is_night = hour >= 22 || hour < 7;

        if !is_night {
            return None;
        }

        Some(Intention {
            id: Uuid::new_v4(),
            intention_type: "ALERT_COLD_NIGHT".to_string(),
            source: "environment".to_string(),
            impact: ImpactLevel::Low,
            context: serde_json::json!({
                "room_id": state.room_id,
                "temperature_c": temp,
                "threshold_c": THRESHOLD_TEMP,
                "time_hour": hour,
                "suggestion": "Température basse la nuit - Augmenter chauffage",
            }),
            created_at: Utc::now().to_rfc3339(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::environment::{EnvReading, RoomEnvironmentState};
    use chrono::{Duration, Utc};

    #[test]
    fn test_evaluate_humidity_alert_triggered() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Add 7 readings with high humidity over 35 minutes (>30 min threshold)
        for i in 0..7 {
            let reading = EnvReading {
                temperature_c: 22.0,
                humidity_pct: 70.0, // Above 65% threshold
                timestamp: Utc::now() - Duration::minutes(35 - i * 5),
            };
            state.update(reading);
        }

        let intention = EnvironmentRules::evaluate_humidity_alert(&state);
        assert!(intention.is_some());

        let intent = intention.unwrap();
        assert_eq!(intent.intention_type, "ALERT_HUMIDITY_CHAMBRE");
        assert_eq!(intent.impact, ImpactLevel::Medium);
        assert_eq!(intent.source, "environment");
    }

    #[test]
    fn test_evaluate_humidity_alert_not_sustained() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Add 2 readings with high humidity, then drop below threshold
        // This simulates humidity spike that doesn't sustain for 30 min
        for i in 0..2 {
            let reading = EnvReading {
                temperature_c: 22.0,
                humidity_pct: 70.0, // High
                timestamp: Utc::now() - Duration::minutes(15 - i * 5),
            };
            state.update(reading);
        }

        // Current reading drops below threshold (not sustained)
        let reading = EnvReading {
            temperature_c: 22.0,
            humidity_pct: 60.0, // Below 65% threshold
            timestamp: Utc::now(),
        };
        state.update(reading);

        let intention = EnvironmentRules::evaluate_humidity_alert(&state);
        assert!(intention.is_none());
    }

    #[test]
    fn test_evaluate_humidity_alert_below_threshold() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Current reading below threshold
        let reading = EnvReading {
            temperature_c: 22.0,
            humidity_pct: 60.0, // Below 65% threshold
            timestamp: Utc::now(),
        };
        state.update(reading);

        let intention = EnvironmentRules::evaluate_humidity_alert(&state);
        assert!(intention.is_none());
    }

    #[test]
    fn test_evaluate_humidity_critical_triggered() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Add 3 readings with critical humidity over 15 minutes (>10 min threshold)
        for i in 0..3 {
            let reading = EnvReading {
                temperature_c: 22.0,
                humidity_pct: 78.0, // Above 75% critical threshold
                timestamp: Utc::now() - Duration::minutes(15 - i * 5),
            };
            state.update(reading);
        }

        let intention = EnvironmentRules::evaluate_humidity_critical(&state);
        assert!(intention.is_some());

        let intent = intention.unwrap();
        assert_eq!(intent.intention_type, "ALERT_HUMIDITY_CRITICAL");
        assert_eq!(intent.impact, ImpactLevel::High);
    }

    #[test]
    fn test_evaluate_cold_night_triggered() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Cold temperature
        let reading = EnvReading {
            temperature_c: 14.0, // Below 16°C
            humidity_pct: 50.0,
            timestamp: Utc::now(),
        };
        state.update(reading);

        // NOTE: This test may fail during daytime (hour 7-22)
        // In production, rule only triggers at night
        let intention = EnvironmentRules::evaluate_cold_night(&state);

        // Check hour to determine expected result
        let hour = Utc::now().hour();
        let is_night = hour >= 22 || hour < 7;

        if is_night {
            assert!(intention.is_some());
            let intent = intention.unwrap();
            assert_eq!(intent.intention_type, "ALERT_COLD_NIGHT");
            assert_eq!(intent.impact, ImpactLevel::Low);
        } else {
            assert!(intention.is_none());
        }
    }

    #[test]
    fn test_evaluate_cold_night_warm_temperature() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Warm temperature
        let reading = EnvReading {
            temperature_c: 20.0, // Above 16°C threshold
            humidity_pct: 50.0,
            timestamp: Utc::now(),
        };
        state.update(reading);

        let intention = EnvironmentRules::evaluate_cold_night(&state);
        assert!(intention.is_none());
    }

    #[test]
    fn test_evaluate_all_multiple_triggered() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Add readings with critical humidity AND cold temp
        for i in 0..3 {
            let reading = EnvReading {
                temperature_c: 14.0, // Cold
                humidity_pct: 78.0,  // Critical humidity
                timestamp: Utc::now() - Duration::minutes(15 - i * 5),
            };
            state.update(reading);
        }

        let intentions = EnvironmentRules::evaluate_all(&state);

        // Should trigger BOTH humidity_critical and cold_night (if night hours)
        assert!(intentions.len() >= 1); // At least humidity critical

        // Verify humidity critical is present
        let has_critical = intentions
            .iter()
            .any(|i| i.intention_type == "ALERT_HUMIDITY_CRITICAL");
        assert!(has_critical);
    }

    #[test]
    fn test_evaluate_all_none_triggered() {
        let state = RoomEnvironmentState::new("chambre".to_string());

        // Default state (20°C, 50% humidity) - no alerts
        let intentions = EnvironmentRules::evaluate_all(&state);
        assert_eq!(intentions.len(), 0);
    }

    #[test]
    fn test_intention_serialization() {
        let intention = Intention {
            id: Uuid::new_v4(),
            intention_type: "ALERT_HUMIDITY_CHAMBRE".to_string(),
            source: "environment".to_string(),
            impact: ImpactLevel::Medium,
            context: serde_json::json!({"room_id": "chambre", "humidity_pct": 70.0}),
            created_at: Utc::now().to_rfc3339(),
        };

        // Test JSON serialization
        let json = serde_json::to_string(&intention).unwrap();
        assert!(json.contains("ALERT_HUMIDITY_CHAMBRE"));
        assert!(json.contains("environment"));

        // Test deserialization
        let deserialized: Intention = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.intention_type, intention.intention_type);
        assert_eq!(deserialized.impact, intention.impact);
    }
}
