/**
 * SYMBION KERNEL - Environment Decision Rules Module (F1) - Dew Point Based
 *
 * RÔLE : Évaluation règles intelligentes humidité/température basées sur physique point de rosée
 *
 * RÈGLES IMPLÉMENTÉES (5 niveaux progressifs) :
 * - ALERT_WEAK      : RH > 55% sustained 6h (Low impact, tendance haute)
 * - ALERT_MODERATE  : RH > 60% sustained 3h (Medium impact, excessive prolongée)
 * - ALERT_STRONG    : RH > 65% for 1h OR deltaT < 3°C for 1h (Medium impact, risque condensation)
 * - ALERT_CRITICAL  : RH > 70% for 20min OR deltaT < 2°C for 20min (High impact, condensation très probable)
 * - ALERT_DANGER    : RH > 75% for 5min OR deltaT ≤ 0°C for 5min (High impact, condensation certaine)
 *
 * PHYSICS BASIS :
 * - Magnus formula pour calcul point de rosée (±0.4°C accuracy)
 * - Delta T = T_surface - T_dew (écart à la condensation)
 * - Estimation T_surface si non disponible (offset configurable)
 *
 * ARCHITECTURE :
 * - Intention : Type simple pour alertes (intention_type, source, impact, context, timestamp)
 * - EnvironmentRules : Struct stateless avec DewPointCalculator interne
 * - Integration : Appelé par MQTT handler lors ingestion readings
 *
 * FUTURE :
 * - Logging intentions to F3 Intentions Log
 * - Notifications via F4 (PWA + Telegram)
 * - ML prediction patterns (F6+)
 */

use crate::decision::types::ImpactLevel;
use crate::dew_point_alerts::{DewPointAlertLevel, DewPointCalculator};
use crate::environment::RoomEnvironmentState;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Intention = Alert generated by environment rules
///
/// Simpler than DecisionEngine Action (no validation workflow for now)
/// Future: Integrate with F3 Intentions Log for persistence
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Intention {
    pub id: Uuid,
    pub intention_type: String, // e.g., "ALERT_WEAK", "ALERT_CRITICAL"
    pub source: String,         // "environment"
    pub impact: ImpactLevel,
    pub context: serde_json::Value, // Room-specific data + physics diagnostics
    pub created_at: String,         // ISO 8601 timestamp
}

/// Environment evaluation rules (stateless) with dew point physics
pub struct EnvironmentRules {
    calculator: DewPointCalculator,
}

impl Default for EnvironmentRules {
    fn default() -> Self {
        Self::new()
    }
}

impl EnvironmentRules {
    /// Create new environment rules evaluator with default dew point calculator
    pub fn new() -> Self {
        Self {
            calculator: DewPointCalculator::new(),
        }
    }

    /// Evaluate all environment rules for a room
    ///
    /// Returns list of triggered intentions (empty if no alerts)
    pub fn evaluate_all(state: &RoomEnvironmentState) -> Vec<Intention> {
        let rules = Self::new();
        let mut intentions = Vec::new();

        // Evaluate dew point based alert
        if let Some(intent) = rules.evaluate_dew_point_alert(state) {
            intentions.push(intent);
        }

        intentions
    }

    /// Main dew point based evaluation
    ///
    /// Uses DewPointCalculator to determine alert level and generate appropriate intention
    fn evaluate_dew_point_alert(&self, state: &RoomEnvironmentState) -> Option<Intention> {
        // Run physics-based evaluation
        let evaluation = self.calculator.evaluate(state);

        // Skip if Safe level
        if evaluation.level == DewPointAlertLevel::Safe {
            return None;
        }

        // Map DewPointAlertLevel to Intention with appropriate impact and context
        let (intention_type, impact, message) = match evaluation.level {
            DewPointAlertLevel::Safe => return None, // Already handled above

            DewPointAlertLevel::Weak => (
                "ALERT_WEAK",
                ImpactLevel::Low,
                "Humidité en tendance haute (>55% depuis 6h) - Surveiller évolution",
            ),

            DewPointAlertLevel::Moderate => (
                "ALERT_MODERATE",
                ImpactLevel::Medium,
                "Humidité excessive prolongée (>60% depuis 3h) - Aérer recommandé",
            ),

            DewPointAlertLevel::Strong => (
                "ALERT_STRONG",
                ImpactLevel::Medium,
                "Risque de condensation détecté (RH >65% ou ΔT <3°C) - Aérer la pièce",
            ),

            DewPointAlertLevel::Critical => (
                "ALERT_CRITICAL",
                ImpactLevel::High,
                "Condensation très probable (RH >70% ou ΔT <2°C) - Action urgente requise",
            ),

            DewPointAlertLevel::Danger => (
                "ALERT_DANGER",
                ImpactLevel::High,
                "Condensation certaine (RH >75% ou ΔT ≤0°C) - Danger moisissure immédiat",
            ),
        };

        // Build comprehensive context with physics data
        let mut context = serde_json::json!({
            "room_id": state.room_id,
            "alert_level": format!("{:?}", evaluation.level),
            "humidity_pct": state.current.humidity_pct,
            "temperature_c": state.current.temperature_c,
            "suggestion": message,
        });

        // Add dew point physics diagnostics if available
        if let Some(dew_point) = evaluation.dew_point_c {
            context["dew_point_c"] = serde_json::json!(dew_point);
        }
        if let Some(delta_t) = evaluation.delta_t {
            context["delta_t"] = serde_json::json!(delta_t);
            context["surface_temp_c"] = serde_json::json!(
                state.current.temperature_c.map(|t| t - self.calculator.config().surface_temp_offset)
            );
        }

        // Add detailed diagnostics from evaluation
        if let serde_json::Value::Object(diag) = &evaluation.diagnostics {
            for (key, value) in diag {
                context[key] = value.clone();
            }
        }

        Some(Intention {
            id: Uuid::new_v4(),
            intention_type: intention_type.to_string(),
            source: "environment".to_string(),
            impact,
            context,
            created_at: chrono::Utc::now().to_rfc3339(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::environment::{EnvReading, RoomEnvironmentState};
    use chrono::{Duration, Utc};

    #[test]
    fn test_evaluate_dew_point_alert_safe() {
        let state = RoomEnvironmentState::new("chambre".to_string());

        // Default state (20°C, 50% humidity) - Safe
        let intentions = EnvironmentRules::evaluate_all(&state);
        assert_eq!(intentions.len(), 0);
    }

    #[test]
    fn test_evaluate_dew_point_alert_weak() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Add readings with RH > 55% for 6+ hours (weak threshold)
        // Need to span from (now - 6h) to now with 30sec intervals
        let now = Utc::now();
        let duration_min = 6 * 60; // 360 minutes = 6 hours
        let num_readings = (duration_min * 2) as usize; // 30sec interval = 720 readings

        for i in 0..num_readings {
            let reading = EnvReading {
                temperature_c: Some(20.0),
                humidity_pct: Some(58.0), // Above 55% threshold
                timestamp: now - Duration::seconds(((duration_min * 60) - (i * 30)) as i64),
            };
            state.update(reading);
        }

        let intentions = EnvironmentRules::evaluate_all(&state);
        assert_eq!(intentions.len(), 1);

        let intent = &intentions[0];
        assert_eq!(intent.intention_type, "ALERT_WEAK");
        assert_eq!(intent.impact, ImpactLevel::Low);
        assert_eq!(intent.source, "environment");
        assert!(intent.context["suggestion"]
            .as_str()
            .unwrap()
            .contains("tendance haute"));
    }

    #[test]
    fn test_evaluate_dew_point_alert_moderate() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Add readings with RH > 60% for 3+ hours
        // Need to span from (now - 3h) to now with 30sec intervals
        let now = Utc::now();
        let duration_min = 3 * 60; // 180 minutes = 3 hours
        let num_readings = (duration_min * 2) as usize; // 30sec interval = 360 readings

        for i in 0..num_readings {
            let reading = EnvReading {
                temperature_c: Some(20.0),
                humidity_pct: Some(62.0), // Above 60% threshold
                timestamp: now - Duration::seconds(((duration_min * 60) - (i * 30)) as i64),
            };
            state.update(reading);
        }

        let intentions = EnvironmentRules::evaluate_all(&state);
        assert_eq!(intentions.len(), 1);

        let intent = &intentions[0];
        assert_eq!(intent.intention_type, "ALERT_MODERATE");
        assert_eq!(intent.impact, ImpactLevel::Medium);
    }

    #[test]
    fn test_evaluate_dew_point_alert_critical() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Add readings with RH > 70% for 20+ minutes (critical threshold)
        // Need to span from (now - 20min) to now with 30sec intervals
        let now = Utc::now();
        let duration_min = 20;
        let num_readings = (duration_min * 2) as usize; // 30sec interval = 40 readings

        for i in 0..num_readings {
            let reading = EnvReading {
                temperature_c: Some(20.0),
                humidity_pct: Some(72.0), // Above 70% critical threshold
                timestamp: now - Duration::seconds(((duration_min * 60) - (i * 30)) as i64),
            };
            state.update(reading);
        }

        let intentions = EnvironmentRules::evaluate_all(&state);
        assert_eq!(intentions.len(), 1);

        let intent = &intentions[0];
        assert_eq!(intent.intention_type, "ALERT_CRITICAL");
        assert_eq!(intent.impact, ImpactLevel::High);
        assert!(intent.context["suggestion"]
            .as_str()
            .unwrap()
            .contains("très probable"));
    }

    #[test]
    fn test_evaluate_dew_point_alert_danger() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Add readings with RH > 75% for 5+ minutes (danger threshold)
        // Need to span from past to very recent with 30sec intervals
        let duration_min = 5;
        let num_readings = (duration_min * 2) as usize; // 30sec interval = 10 readings

        for i in 0..num_readings {
            let reading = EnvReading {
                temperature_c: Some(20.0),
                humidity_pct: Some(78.0), // Above 75% danger threshold
                timestamp: Utc::now() - Duration::seconds(((duration_min * 60) - (i * 30)) as i64),
            };
            state.update(reading);
        }

        // Add current reading to ensure freshness
        let reading = EnvReading {
            temperature_c: Some(20.0),
            humidity_pct: Some(78.0),
            timestamp: Utc::now(),
        };
        state.update(reading);

        let intentions = EnvironmentRules::evaluate_all(&state);
        assert_eq!(intentions.len(), 1);

        let intent = &intentions[0];
        assert_eq!(intent.intention_type, "ALERT_DANGER");
        assert_eq!(intent.impact, ImpactLevel::High);
        assert!(intent.context["suggestion"]
            .as_str()
            .unwrap()
            .contains("Condensation certaine"));
    }

    #[test]
    fn test_intention_contains_dew_point_diagnostics() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Critical humidity - need proper time span for 20min requirement
        let now = Utc::now();
        let duration_min = 20;
        let num_readings = (duration_min * 2) as usize; // 30sec interval = 40 readings

        for i in 0..num_readings {
            let reading = EnvReading {
                temperature_c: Some(18.0),
                humidity_pct: Some(72.0),
                timestamp: now - Duration::seconds(((duration_min * 60) - (i * 30)) as i64),
            };
            state.update(reading);
        }

        let intentions = EnvironmentRules::evaluate_all(&state);
        assert_eq!(intentions.len(), 1);

        let intent = &intentions[0];

        // Should contain physics diagnostics
        assert!(intent.context["dew_point_c"].is_number());
        assert!(intent.context["delta_t"].is_number());
        assert!(intent.context["surface_temp_c"].is_number());
        assert!(intent.context["humidity_pct"].is_number());

        // Verify dew point calculation is reasonable
        let dew_point = intent.context["dew_point_c"].as_f64().unwrap();
        assert!(dew_point > 10.0 && dew_point < 20.0); // Reasonable range for 18°C, 72% RH
    }

    #[test]
    fn test_intention_serialization() {
        let intention = Intention {
            id: Uuid::new_v4(),
            intention_type: "ALERT_WEAK".to_string(),
            source: "environment".to_string(),
            impact: ImpactLevel::Low,
            context: serde_json::json!({"room_id": "chambre", "humidity_pct": 58.0}),
            created_at: chrono::Utc::now().to_rfc3339(),
        };

        // Test JSON serialization
        let json = serde_json::to_string(&intention).unwrap();
        assert!(json.contains("ALERT_WEAK"));
        assert!(json.contains("environment"));

        // Test deserialization
        let deserialized: Intention = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.intention_type, intention.intention_type);
        assert_eq!(deserialized.impact, intention.impact);
    }

    #[test]
    fn test_no_alert_when_humidity_drops_quickly() {
        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // High humidity for a while
        for i in 0..3 {
            let reading = EnvReading {
                temperature_c: Some(20.0),
                humidity_pct: Some(70.0),
                timestamp: Utc::now() - Duration::minutes((15 - i * 5) as i64),
            };
            state.update(reading);
        }

        // Then drops below threshold (current reading is what counts)
        let reading = EnvReading {
            temperature_c: Some(20.0),
            humidity_pct: Some(50.0), // Dropped to safe level
            timestamp: Utc::now(),
        };
        state.update(reading);

        let intentions = EnvironmentRules::evaluate_all(&state);
        assert_eq!(
            intentions.len(),
            0,
            "No alert should trigger when current humidity is safe"
        );
    }

    #[test]
    fn test_alert_levels_prioritization() {
        // Test that higher alert levels take precedence

        let mut state = RoomEnvironmentState::new("chambre".to_string());

        // Create condition that could trigger multiple levels
        // RH = 76% triggers Danger (highest) - need proper 5min span
        let duration_min = 5;
        let num_readings = (duration_min * 2) as usize; // 30sec interval = 10 readings

        for i in 0..num_readings {
            let reading = EnvReading {
                temperature_c: Some(20.0),
                humidity_pct: Some(76.0), // Triggers all levels, but Danger is highest
                timestamp: Utc::now() - Duration::seconds(((duration_min * 60) - (i * 30)) as i64),
            };
            state.update(reading);
        }

        // Add current reading to ensure freshness
        let reading = EnvReading {
            temperature_c: Some(20.0),
            humidity_pct: Some(76.0),
            timestamp: Utc::now(),
        };
        state.update(reading);

        let intentions = EnvironmentRules::evaluate_all(&state);

        // Should only return highest level alert (Danger)
        assert_eq!(intentions.len(), 1);
        assert_eq!(intentions[0].intention_type, "ALERT_DANGER");
    }
}
